import Link from 'next/link';
import { getTranslations } from 'next-intl/server';
import { Shield, Zap, Target, Sparkles, Smartphone, ImageIcon, Lock, Eye, CheckCircle } from 'lucide-react';

interface HomeStaticContentProps {
    locale: string;
}

export default async function HomeStaticContent({ locale }: HomeStaticContentProps) {
    const isZh = locale === 'zh';
    const t = await getTranslations({ locale, namespace: 'features' });
    const s = await getTranslations({ locale, namespace: 'sections' });

    return (
        <>
            {/* SECTION 2: 专注 "Gemini Logo Remover" (E-E-A-T: Experience & Expertise) */}
            <LogoRemoverSection isZh={isZh} s={s} />

            {/* SECTION 3: 专注 "Gemini Watermark Remover" (E-E-A-T: Authority & Tech) */}
            <WatermarkRemoverSection isZh={isZh} s={s} />

            {/* Features Section */}
            <FeaturesSection t={t} />

            {/* FAQ Section */}
            <FAQSection isZh={isZh} />

            {/* CTA Section */}
            <CTASection isZh={isZh} locale={locale} />
        </>
    );
}

function LogoRemoverSection({ isZh, s }: { isZh: boolean; s: any }) {
    return (
        <section id="logo-remover" className="w-full py-20 bg-secondary/20">
            <div className="container mx-auto px-4 grid md:grid-cols-2 gap-12 items-center max-w-6xl">
                <div>
                    {/* 视觉证据：占位图，后续可替换为 CompareSlider */}
                    <div className="rounded-xl overflow-hidden border-4 border-white shadow-lg transform -rotate-1 hover:rotate-0 transition duration-500 bg-muted aspect-video flex items-center justify-center">
                        <div className="text-center p-8">
                            <Eye className="w-16 h-16 mx-auto text-muted-foreground mb-4" />
                            <p className="text-muted-foreground">Before & After Demo</p>
                        </div>
                    </div>
                    <p className="text-center text-sm text-muted-foreground mt-2">Before & After: Corner Logo Removal</p>
                </div>

                <div className="space-y-6">
                    {/* H2 精准匹配 */}
                    <h2 className="text-3xl font-bold">
                        {isZh ? '为什么需要专门的' : 'Why a Specialized'}{' '}
                        <span className="text-yellow-600">Gemini Logo Remover</span>
                        {isZh ? '？' : '?'}
                    </h2>
                    <p className="text-muted-foreground">
                        {s('logo_desc')}
                    </p>
                    <ul className="space-y-3">
                        <li className="flex gap-3">
                            <CheckCircle className="w-5 h-5 text-green-500 flex-shrink-0 mt-1" />
                            <span><strong>{isZh ? '结构重建：' : 'Structure Reconstruction:'}</strong> {isZh ? '我们重新绘制 Logo 后面的背景纹理。' : 'We redraw the background texture behind the logo.'}</span>
                        </li>
                        <li className="flex gap-3">
                            <CheckCircle className="w-5 h-5 text-green-500 flex-shrink-0 mt-1" />
                            <span><strong>{isZh ? '文字和图标定位：' : 'Text & Icon Targeting:'}</strong> {isZh ? '专门针对星形图标和 "Generated by Gemini" 文字进行训练。' : 'Specifically trained on the "star" icon and "Generated by Gemini" text.'}</span>
                        </li>
                    </ul>
                    {/* 密度控制：再次提及关键词 */}
                    <p className="text-muted-foreground">
                        {isZh
                            ? '这使我们的工具成为最精准的免费 '
                            : 'This makes our tool the most precise '}
                        <strong>Gemini Logo Remover</strong>
                        {isZh ? '。' : ' available for free.'}
                    </p>
                </div>
            </div>
        </section>
    );
}

function WatermarkRemoverSection({ isZh, s }: { isZh: boolean; s: any }) {
    return (
        <section id="watermark-remover" className="w-full py-20 px-4">
            <div className="container mx-auto max-w-5xl text-center">
                <h2 className="text-3xl font-bold mb-6">
                    {isZh ? '不仅仅是 Logo：完整的' : 'More Than Just a Logo: A Full'}{' '}
                    <span className="text-orange-600">Gemini Watermark Remover</span>
                </h2>
                <p className="text-lg text-muted-foreground mb-10 max-w-3xl mx-auto">
                    {s('watermark_desc')}
                </p>

                {/* 技术展示卡片 - 展示专业度 (Expertise) */}
                <div className="grid md:grid-cols-3 gap-6 text-left">
                    <div className="p-6 border rounded-xl bg-card hover:shadow-md transition">
                        <Zap className="w-10 h-10 text-yellow-500 mb-4" />
                        <h3 className="font-bold text-xl mb-2">{s('synthid_title')}</h3>
                        <p className="text-sm text-muted-foreground">{s('synthid_desc')}</p>
                    </div>
                    <div className="p-6 border rounded-xl bg-card hover:shadow-md transition">
                        <Shield className="w-10 h-10 text-blue-500 mb-4" />
                        <h3 className="font-bold text-xl mb-2">{s('metadata_title')}</h3>
                        <p className="text-sm text-muted-foreground">{s('metadata_desc')}</p>
                    </div>
                    <div className="p-6 border rounded-xl bg-card hover:shadow-md transition">
                        <ImageIcon className="w-10 h-10 text-purple-500 mb-4" />
                        <h3 className="font-bold text-xl mb-2">{s('export_title')}</h3>
                        <p className="text-sm text-muted-foreground">
                            {isZh
                                ? '与其他 Gemini 水印去除器工具不同，我们不会压缩您的画质。'
                                : 'Unlike other '}
                            {!isZh && <strong>Gemini Watermark Remover</strong>}
                            {!isZh && ' tools, we don\'t compress your quality.'}
                        </p>
                    </div>
                </div>
            </div>
        </section>
    );
}

function FeaturesSection({ t }: { t: any }) {
    const features = [
        { icon: Lock, title: t('feature_1_title'), desc: t('feature_1_desc') },
        { icon: Zap, title: t('feature_2_title'), desc: t('feature_2_desc') },
        { icon: Target, title: t('feature_3_title'), desc: t('feature_3_desc') },
        { icon: Sparkles, title: t('feature_4_title'), desc: t('feature_4_desc') },
        { icon: Smartphone, title: t('feature_5_title'), desc: t('feature_5_desc') },
        { icon: ImageIcon, title: t('feature_6_title'), desc: t('feature_6_desc') },
    ];

    return (
        <section id="features" className="py-20 bg-muted/20">
            <div className="container px-4 md:px-6">
                <div className="mx-auto max-w-6xl space-y-12 text-center">
                    <div className="space-y-4">
                        <h2 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
                            {t('title')}
                        </h2>
                        <p className="mx-auto max-w-3xl text-muted-foreground text-lg">
                            {t('subtitle')}
                        </p>
                    </div>

                    <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
                        {features.map((feature, idx) => {
                            const Icon = feature.icon;
                            return (
                                <div
                                    key={idx}
                                    className="rounded-2xl bg-background p-8 shadow-sm border border-border hover:shadow-md transition-shadow"
                                >
                                    <div className="space-y-4">
                                        <div className="inline-flex h-12 w-12 items-center justify-center rounded-full bg-yellow-500/10">
                                            <Icon className="w-6 h-6 text-yellow-600" />
                                        </div>
                                        <h3 className="text-xl font-bold text-foreground">{feature.title}</h3>
                                        <p className="text-muted-foreground">{feature.desc}</p>
                                    </div>
                                </div>
                            );
                        })}
                    </div>
                </div>
            </div>
        </section>
    );
}

function FAQSection({ isZh }: { isZh: boolean }) {
    const faqs = isZh ? [
        {
            q: "如何使用 Gemini Logo Remover 去除角落 Logo？",
            a: "1. 上传您的 Gemini 生成图片\n2. 用画笔工具涂抹角落的 Logo 区域\n3. 点击\"去除水印\"按钮\n4. 下载处理后的干净图片"
        },
        {
            q: "这个 Gemini Watermark Remover 是免费的吗？",
            a: "是的，完全免费使用。没有隐藏费用，没有水印，也不需要注册账号。"
        },
        {
            q: "我的图片安全吗？",
            a: "绝对安全！所有图片处理都在您的浏览器本地完成，从不上传到任何服务器。您的图片和隐私得到 100% 保护。"
        },
        {
            q: "可以去除 SynthID 隐形水印吗？",
            a: "我们的 Gemini Watermark Remover 工具可以处理可见的水印和 Logo。对于 SynthID 等隐形数字水印，我们通过图像重处理技术来减轻其影响。"
        }
    ] : [
        {
            q: "How do I use the Gemini Logo Remover to erase corner logos?",
            a: "1. Upload your Gemini-generated image\n2. Use the brush tool to paint over the corner logo area\n3. Click the 'Remove Watermark' button\n4. Download your clean image"
        },
        {
            q: "Is this Gemini Watermark Remover free?",
            a: "Yes, completely free to use. No hidden fees, no watermarks on output, and no registration required."
        },
        {
            q: "Are my images safe?",
            a: "Absolutely! All image processing happens locally in your browser. Nothing is uploaded to any server. Your images and privacy are 100% protected."
        },
        {
            q: "Can it remove SynthID invisible watermarks?",
            a: "Our Gemini Watermark Remover tool can process visible watermarks and logos. For invisible digital watermarks like SynthID, we use image reprocessing techniques to reduce their impact."
        }
    ];

    return (
        <section className="py-20 bg-background border-t">
            <div className="container px-4 md:px-6">
                <div className="max-w-4xl mx-auto space-y-12">
                    <div className="text-center space-y-4">
                        <h2 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
                            {isZh ? '常见问题' : 'Frequently Asked Questions'}
                        </h2>
                    </div>

                    <div className="grid gap-6">
                        {faqs.map((faq, idx) => (
                            <div key={idx} className="bg-muted/30 rounded-lg p-6 space-y-3 border border-border">
                                <h3 className="text-xl font-bold">{faq.q}</h3>
                                <div className="text-muted-foreground whitespace-pre-line leading-relaxed">
                                    {faq.a}
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </section>
    );
}

function CTASection({ isZh, locale }: { isZh: boolean; locale: string }) {
    return (
        <section className="py-20 bg-gradient-to-b from-yellow-50/50 to-background dark:from-yellow-950/20 dark:to-background">
            <div className="container px-4 md:px-6">
                <div className="mx-auto max-w-4xl text-center space-y-8">
                    <div className="space-y-6">
                        <h2 className="text-4xl font-bold tracking-tight text-foreground sm:text-5xl">
                            {isZh ? '立即开始去除 Gemini 水印' : 'Start Removing Gemini Watermarks Now'}
                        </h2>
                        <p className="mx-auto max-w-2xl text-muted-foreground text-lg">
                            {isZh
                                ? '免费、快速、完全私密。无需注册，立即使用我们的 Gemini Logo Remover。'
                                : 'Free, fast, and completely private. Try our Gemini Logo Remover - no sign-up required.'}
                        </p>
                        <div className="flex flex-wrap justify-center gap-4 pt-4">
                            <Link
                                href={`/${locale}`}
                                className="px-8 py-4 rounded-full bg-gradient-to-r from-yellow-500 to-orange-500 text-white hover:opacity-90 transition-opacity font-medium text-lg shadow-lg"
                            >
                                {isZh ? '上传图片开始' : 'Upload Image to Start'}
                            </Link>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    );
}
